### ISSUE TITLE
Command Failed: git clone

### ISSUE THREAD

**Issue by arjunpola** [forcedotcom/SmartSyncExplorerReactNative#101]
When I run `node ./installios.js` I get the following error.

```
Error: Command failed: git clone --branch v5.2.0 --single-branch --depth 1 --recurse-submodules=external/fmdb https://github.com/forcedotcom/SalesforceMobileSDK-iOS.git mobile_sdk/salesforcemobilesdk-ios
    at checkExecSyncError (child_process.js:490:13)
    at execSync (child_process.js:530:13)
    at Object.<anonymous> (/Users/nagarjunpola/TM-RN/SmartSyncExplorerReactNative/installios.js:16:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
```

The issue seems to be with `--recurse-submodules=external/fmdb` option. I could bypass the error by changing the option to `--recurse-submodules`.

**Comment by wmathurin** [comment]
You need git 2.13.0 and above for ```--recurse-submodules[=<pathspec]``` to work.
